language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - AUTOLOAD=1
  - AUTOLOAD=0

before_script: composer install -n --dev --prefer-source

after_script: ./vendor/bin/coveralls -v